### ISSUE TITLE
Не удалось найти сертификат электронной подписи c серийным номером

### ISSUE THREAD

**Issue by Krasnoe-Beloe** [alfa-laboratory/alfalink-1c-directbank-via-1c#1]
Здравствуйте, 

Тестируем обмен с банком из 1с по системе Директ банк, скачал тестовый сертификат по ссылке: 

https://github.com/alfa-laboratory/alfalink-1c-directbank-via-1c/archive/refs/heads/master.zip

На прошлой неделе (10-09-2021) все было норм, с понедельника (13-09-2021) при подписи тестового документа из банка приходит ответ: 

Получена ошибка из банка (13.09.2021 11:39:23). Код ошибки 1101.
Сертификат электронной подписи не найден: Не удалось найти сертификат электронной подписи c серийным номером 12005648E7EFE43719D07295240001005648E7

Сам сертификат проверку проходит полностью:

![img-2021-09-13-11-59-09](https://user-images.githubusercontent.com/90600131/133038018-021f97d8-883f-4245-8e89-5fc2367650b1.png)

Подскажите какой тестовый сертификат нужно установить?

**Comment by artik008** [comment]
Добрый день!
Сертификат восстановили, проверьте, пожалуйста.

**Comment by Krasnoe-Beloe** [comment]
> Добрый день!
> Сертификат восстановили, проверьте, пожалуйста.

Да, работает. Спасибо!
